#!/bin/bash
export BIN="/usr/local/bin"
export EXEC_DIR="$BIN/bash-package-manager"
export SRC="$EXEC_DIR/src"
export COMMON="$EXEC_DIR/common"
export BCS="$PWD/.bpm"
export BCS_MODULES="$PWD/bpm_modules"
export PACKAGELEE="$PWD/package.lee"
export API="https://annalee.rbrtbrnschn.dev/api"
export DEBUG=0
export ERROR=0
export INFO=0

function debug {
	export EXEC_DIR="$PWD"
	export SRC="$EXEC_DIR/src"
	export COMMON="$EXEC_DIR/common"
	export DEBUG=1
}

while getopts ":-:" OPTION; do
	case $OPTION in
		-)
			case $OPTARG in
				debug)
					debug
					shift
				;;
			esac
		;;
	esac
done
$SRC/loggers.sh

export VALID_COMMANDS="help init install i version list remove rm upload purge key clean_list"
COMMAND="$1" && shift
ARGS="$*" && shift $#

[[ "$VALID_COMMANDS" =~ "$COMMAND" && -f "$SRC/$COMMAND.sh" ]] && $SRC/$COMMAND.sh $ARGS || [ -f "$SRC/$COMMAND.help" ] && "$SRC/$COMMAND.help" || "$SRC/help.sh"

