#!/bin/bash

# creating custom directory
RAND_DIR="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
export TMP_DIR="/tmp/$RAND_DIR"
mkdir $TMP_DIR
echo "$TMP_DIR"

# handle cleanup
function handle_exit {
	rm -rf $TMP_DIR
}
trap handle_exit 0 1 SIGHUP SIGINT SIGQUIT SIGABRT SIGTERM
exit 2
